package com.redhat.training.resources.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;

import com.redhat.training.model.customer.Customer;

/**
 * This class was generated by Apache CXF 2.4.6-redhat-1
 * 2013-02-06T10:31:45.837-05:00 Generated source version: 2.4.6-redhat-1
 * 
 */
@WebService
@SOAPBinding(style = Style.RPC)
public interface SaveCustomerInformationService {

	@WebMethod
	public void saveCustomerInformation(@WebParam(name = "customer", partName = "Customer") Customer customer)
			throws Exception;

	@WebMethod
	public void updateCustomerInformation(@WebParam(name = "customer", partName = "Customer") Customer customer);

}
