package com.redhat.training.resources.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.6-redhat-1
 * 2013-02-06T10:31:45.892-05:00 Generated source version: 2.4.6-redhat-1
 * 
 */
//@WebServiceClient(name = "SaveCustomerInformationService", targetNamespace = "http://www.theforce.org/", wsdlLocation = "http://localhost:8080/SaveCustomerInformationService?wsdl")
@Deprecated
public class SaveCustomerInformationServiceService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://www.theforce.org/", "SaveCustomerInformationService");
	static {
		URL url = null;
		try {
			url = new URL("http://localhost:8080/customer-information/SaveCustomerInformationService?wsdl");
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		WSDL_LOCATION = url;
	}

	public SaveCustomerInformationServiceService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public SaveCustomerInformationServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SaveCustomerInformationServiceService() {
		super(WSDL_LOCATION, SERVICE);
	}

	public SaveCustomerInformationService getSaveCustomerInformationClientEnpoint() {
		return super.getPort(SERVICE, SaveCustomerInformationService.class);

	}

	public SaveCustomerInformationService getSaveCustomerInformationClientEnpoint(WebServiceFeature... features) {
		return super.getPort(SERVICE, SaveCustomerInformationService.class, features);

	}
}
